"""empty message

Revision ID: 64a35672e1e5
Revises: 8ed1ae12bd1e
Create Date: 2018-03-29 16:50:34.378717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a35672e1e5'
down_revision = '8ed1ae12bd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_post_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'parent_post_id')
    # ### end Alembic commands ###
