"""empty message

Revision ID: 8ed1ae12bd1e
Revises: 4d8be9c88f4c
Create Date: 2018-03-29 14:35:54.625445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed1ae12bd1e'
down_revision = '4d8be9c88f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('baths', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('beds', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('build_type', sa.String(length=50), nullable=True))
    op.add_column('project', sa.Column('lotsqft', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('num_units', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('property_type', sa.String(length=50), nullable=True))
    op.add_column('project', sa.Column('sqft', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('year_built', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('year_renovated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'year_renovated')
    op.drop_column('project', 'year_built')
    op.drop_column('project', 'sqft')
    op.drop_column('project', 'property_type')
    op.drop_column('project', 'num_units')
    op.drop_column('project', 'lotsqft')
    op.drop_column('project', 'build_type')
    op.drop_column('project', 'beds')
    op.drop_column('project', 'baths')
    # ### end Alembic commands ###
